#!/bin/sh

. /lib/functions.sh

CTRL="/var/run/wpa_supplicant"

if [ "${ACTION}" = "add" -a "$(uci -q get wireless.${DEVICENAME}.network)" = "wifi" -a "$(uci -q get wireless.${DEVICENAME}.mode)" = "sta" ]; then
    radio=$(echo ${DEVICENAME} | sed s/wlan/radio/)
    channels="$(uci -q -c /etc/config.mesh get setup.globals.${radio}_channels)"
    if [ "${channels}" != "${channels#* }" ]; then
        # Wait for the socket to become available
        count=0
        while [ ! -S "${CTRL}/${DEVICENAME}" -a ${count} -lt 10 ]; do
            sleep 1
            count=$((count+1))
        done
        if [ -S "${CTRL}/${DEVICENAME}" ]; then
            # Once it is, add the ssids for the channel selection
            bandwidth="$(uci -q -c /etc/config.mesh get setup.globals.${radio}_bandwidth)"
            ssid="$(uci -q -c /etc/config.mesh get setup.globals.${radio}_ssid)"
            wpa_cli -i "${DEVICENAME}" -p "${CTRL}" remove_network all
            for channel in ${channels}
            do
                id=$(wpa_cli -i "${DEVICENAME}" -p "${CTRL}" add_network | tail -1)
                wpa_cli -i "${DEVICENAME}" -p "${CTRL}" set_network "${id}" ssid "\"${ssid}-${channel}-${bandwidth}-v3\""
                wpa_cli -i "${DEVICENAME}" -p "${CTRL}" set_network "${id}" key_mgmt NONE
                wpa_cli -i "${DEVICENAME}" -p "${CTRL}" enable_network "${id}"
            done
            wpa_cli -i "${DEVICENAME}" -p "${CTRL}" reassociate
        fi
    fi
fi
